trigger:
- master

pool:
  name: Default

variables:
  buildConfiguration: 'Release'

stages:

# BUILD + TEST + ANALYSIS
- stage: BuildAndTest
  displayName: Build Test and Analysis

  jobs:
  - job: BuildJob
    displayName: Build Job

    steps:

    - task: UseDotNet@2
      displayName: Install .NET SDK
      inputs:
        packageType: 'sdk'
        version: '8.x'

    - script: dotnet restore
      displayName: Restore Dependencies

    - script: dotnet build --configuration $(buildConfiguration)
      displayName: Build Application

    - script: dotnet test --collect:"XPlat Code Coverage"
      displayName: Run Unit Tests with Coverage

    - script: dotnet format --verify-no-changes
      displayName: Static Code Analysis


# DEPLOY
- stage: Deploy
  displayName: Deploy Application
  dependsOn: BuildAndTest
  condition: succeeded()

  jobs:
  - job: DeployJob
    displayName: Deploy Containers

    steps:

    - script: docker compose -f DevOpsApi/docker-compose.yml down
      displayName: Stop Existing Containers
      workingDirectory: $(Build.SourcesDirectory)

    - script: docker compose -f DevOpsApi/docker-compose.yml up -d --build
      displayName: Deploy with Docker Compose
      workingDirectory: $(Build.SourcesDirectory)
      
    - script: docker ps
      displayName: Validate Running Containers