trigger:
  branches:
    include:
      - main

  tags:
    include:
      - v*

pool:
  name: Default

variables:
  buildConfiguration: 'Release'

stages:

# BUILD
- stage: Build
  displayName: Build Stage

  jobs:
  - job: BuildJob

    steps:

    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '8.x'

    - script: dotnet restore
      displayName: Restore Dependencies

    - script: dotnet build --configuration $(buildConfiguration)
      displayName: Build Application

# TEST
- stage: Test
  displayName: Test Stage
  dependsOn: Build

  jobs:
  - job: TestJob

    steps:

    - script: dotnet test --collect:"XPlat Code Coverage"
      displayName: Run Tests

    - script: dotnet format --verify-no-changes
      displayName: Static Analysis

# DEPLOY DEV
- stage: DeployDev
  displayName: Deploy Development
  dependsOn: Test

  jobs:
  - job: DeployDevJob

    steps:

    - script: docker compose -f DevOpsApi\docker-compose.dev.yml down
      workingDirectory: $(Build.SourcesDirectory)
      displayName: Stop DEV

    - script: docker compose -f DevOpsApi\docker-compose.dev.yml up -d --build
      workingDirectory: $(Build.SourcesDirectory)
      displayName: Deploy DEV

# DEPLOY PROD
- stage: DeployProd
  displayName: Deploy Production
  dependsOn: DeployDev
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')

  jobs:
  - job: DeployProdJob

    steps:

    - script: docker compose -f DevOpsApi\docker-compose.prod.yml down
      workingDirectory: $(Build.SourcesDirectory)
      displayName: Stop PROD

    - script: docker compose -f  DevOpsApi\docker-compose.prod.yml up -d --build
      workingDirectory: $(Build.SourcesDirectory)
      displayName: Deploy PROD

    - script: docker ps
      displayName: Validate Containers